### ISSUE TITLE
Travis Linux builds failing: can't find FFTW

### ISSUE THREAD

**Issue by MarkWieczorek** [SHTOOLS/SHTOOLS#152]
The Travis Linux builds started to fail for no apparent reason. It appears that `numpy.distutils.system_info.get_info()` is not able to find FFTW, which was installed by apt-get. This same problem arose with the OSX builds, but this was easy to fix by setting the environment variable FFTW to /usr/local. I have tried setting FFTW to /usr, /usr/local/, /usr/local/lib, opt/ and $PATH, with no effect.

The full travis log is here: https://travis-ci.org/SHTOOLS/SHTOOLS/jobs/388239380

Below is the relevant part.
~~~~
$ pip install --no-deps .
Processing /home/travis/build/SHTOOLS/SHTOOLS
    Complete output from command python setup.py egg_info:
    pandoc is not installed. PYPI description will not be formatted correctly.
    INSTALLING SHTOOLS 4.3.dev0+ec65611
    get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
    customize Gnu95FCompiler
    Found executable /usr/bin/gfortran
    get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
    customize Gnu95FCompiler
    searching SHTOOLS in: build/temp.linux-x86_64-3.6
    fftw_info:
    customize UnixCCompiler
      libraries fftw3 not found in ['/usr/lib', '/home/travis/miniconda/envs/test-environment/lib']
      fftw3 not found
    customize UnixCCompiler
      libraries rfftw,fftw not found in ['/usr/lib', '/home/travis/miniconda/envs/test-environment/lib']
      fftw2 not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-bvn7z0zn/setup.py", line 288, in <module>
        setup(**metadata)
      File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-req-build-bvn7z0zn/setup.py", line 243, in configuration
        fftw_info = get_info('fftw', notfound_action=2)
      File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/numpy/distutils/system_info.py", line 432, in get_info
        return cl().get_info(notfound_action)
      File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/numpy/distutils/system_info.py", line 630, in get_info
        raise self.notfounderror(self.notfounderror.__doc__)
    numpy.distutils.system_info.FFTWNotFoundError:
        FFTW (http://www.fftw.org/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [fftw]) or by setting
        the FFTW environment variable.
~~~~

**Comment by MarkWieczorek** [comment]
https://github.com/travis-ci/travis-ci/issues/9708

**Comment by MarkWieczorek** [comment]
Note: As a temporary fix, I have installed FFTW using conda instead of apt-get. This fixes this immediate problem with Travis, but it appears that there is a bigger issue with how FFTW is being treated by mupy's distutils (see https://github.com/SHTOOLS/SHTOOLS/issues/147).

**Comment by MarkWieczorek** [comment]
I just tried reverting back to the old way, and it now works. Travis must have fixed this in the meantime.

**Comment by svretina** [comment]
Encountering this issue on a Fedora installation. Any suggestion to install pyshtools?
