### ISSUE TITLE
Deprectation of distutils module(Python 3.12)

### ISSUE THREAD

**Issue by MarkWieczorek** [SHTOOLS/SHTOOLS#345]
The `distutils` module will be deprecated with the release of Python 3.12: https://peps.python.org/pep-0632/

This will probably affect `numpy.distutils`as well, but they will likely support this for a longer period of time: https://github.com/numpy/numpy/issues/18588

pyshtools makes use of `numpy.distutils` in the setup.py file, so we should probably start thinking about whether we should deal with this.

**Comment by QuLogic** [comment]
Meson could build both the Fortran and Python side of things together (with option to bundle or not.) I'm not sure how well the Python distribution integration is though, so would perhaps wait until SciPy has figured out their first release with it.

**Comment by jo-mueller** [comment]
I'm not sure whether it's related, but sounds a bit like it:

I have pyshtools in the dependencies of [another package](https://github.com/BiAPoL/napari-stress), the github CI for which fails with a numpy error (Traceback below). Pinning pyshtools to `<=4.10.0` solved the problem (see [issue](https://github.com/BiAPoL/napari-stress/issues/155)). 

Github CI traceback:

```
Collecting pyshtools
  Downloading pyshtools-4.10.1.tar.gz (38.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.1/38.1 MB 40.0 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-haflr32o/pyshtools_0fae6e73f1e84be9b6922820eeaeb7c6/setup.py", line 21, in <module>
          import numpy  # noqa: E402
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
```

**Comment by rgommers** [comment]
FYI, SciPy 1.9 is built with Meson, and all of the major issues around Fortran, f2py and around building wheels are resolved. The end result is quite a bit nicer than what you can get with `distutils`. This is probably a good time to start moving.

**Comment by QuLogic** [comment]
The compiled part is pretty straightforward; I put that together in [this meson branch](https://github.com/QuLogic/SHTOOLS/tree/meson), but this does _not_ include any Python metadata. With that, I am able to do:
```
$ meson setup -Dblas=flexiblas -Dlapack=flexiblas build
The Meson build system
Version: 0.62.1
Source dir: /home/elliott/code/SHTOOLS
Build dir: /home/elliott/code/SHTOOLS/build
Build type: native build
Project name: shtools
Project version: 4.11.0
Fortran compiler for the host machine: gfortran (gcc 12.1.1 "GNU Fortran (GCC) 12.1.1 20220507 (Red Hat 12.1.1-1)")
Fortran linker for the host machine: gfortran ld.bfd 2.37-27
C compiler for the host machine: ccache cc (gcc 12.1.1 "cc (GCC) 12.1.1 20220507 (Red Hat 12.1.1-1)")
C linker for the host machine: cc ld.bfd 2.37-27
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Run-time dependency flexiblas found: YES 3.2.0
Dependency flexiblas found: YES 3.2.0 (cached)
Run-time dependency fftw3 found: YES 3.3.10
Program python3 (numpy) found: YES (/usr/bin/python3) modules: numpy
C++ compiler for the host machine: ccache c++ (gcc 12.1.1 "c++ (GCC) 12.1.1 20220507 (Red Hat 12.1.1-1)")
C++ linker for the host machine: c++ ld.bfd 2.37-27
Build targets in project: 15

shtools 4.11.0

  User defined options
    blas  : flexiblas
    lapack: flexiblas

Found ninja-1.10.2 at /usr/bin/ninja

$ ninja -C build
ninja: Entering directory `build'
[122/147] Generating pyshtools/pyshtools_c with a custom command
... a bunch of stuff from f2py ...
[123/147] Compiling Fortran object examples/fortran/SHRotate/TestSHRotate.p/TestSHRotate.f95.o
../examples/fortran/SHRotate/TestSHRotate.f95:92:11:

   92 |     nlat = 180.0_dp / interval + 1
      |           1
Warning: Possible change of value in conversion from REAL(8) to INTEGER(4) at (1) [-Wconversion]
../examples/fortran/SHRotate/TestSHRotate.f95:93:12:

   93 |     nlong = 360.0_dp / interval + 1
      |            1
Warning: Possible change of value in conversion from REAL(8) to INTEGER(4) at (1) [-Wconversion]
[125/147] Compiling C object pyshtools/_SHTOOLS.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__SHTOOLSmodule.c.o
pyshtools/_SHTOOLSmodule.c:202:12: warning: ‘f2py_size’ defined but not used [-Wunused-function]
  202 | static int f2py_size(PyArrayObject* var, ...)
      |            ^~~~~~~~~
[146/147] Compiling Fortran object pyshtools/_SHTOOLS.cpython-310-x86_64-linux-gnu.so.p/.._src_PythonWrapper.f95.o
../src/PythonWrapper.f95:626:62:

  626 |     subroutine pySHRead2(exitstatus,filename,cilm,lmax,lmax_in,gm,r0_pot,dot,&
      |                                                              1
Warning: Unused dummy argument ‘lmax_in’ at (1) [-Wunused-dummy-argument]
../src/PythonWrapper.f95:653:73:

  653 |     subroutine pySHRead2Error(exitstatus,filename,cilm,error,lmax,lmax_in,gm,&
      |                                                                         1
Warning: Unused dummy argument ‘lmax_in’ at (1) [-Wunused-dummy-argument]
../src/PythonWrapper.f95:686:64:

  686 |     subroutine pySHReadJPL(exitstatus,filename,cilm,lmax,lmax_in,gm,&
      |                                                                1
Warning: Unused dummy argument ‘lmax_in’ at (1) [-Wunused-dummy-argument]
../src/PythonWrapper.f95:705:75:

  705 |     subroutine pySHReadJPLError(exitstatus,filename,cilm,error,lmax,lmax_in,&
      |                                                                           1
Warning: Unused dummy argument ‘lmax_in’ at (1) [-Wunused-dummy-argument]
[147/147] Linking target pyshtools/_SHTOOLS.cpython-310-x86_64-linux-gnu.so

$ ninja -C build test
ninja: Entering directory `build'
[0/1] Running all tests.
1/7 MarsCrustalThickness        OK              2.66s
2/7 ExpandDH                    OK              2.76s
3/7 LocalizedAdmitCorr          OK              0.19s
4/7 SHRotate                    OK              1.07s
5/7 SHExpandLSQ                 OK             10.00s
6/7 SHMag                       OK              8.94s
7/7 CilmPlus                    OK             26.18s


Ok:                 7   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /home/elliott/code/SHTOOLS/build/meson-logs/testlog.txt
```
I can also run `ninja -C build benchmark` and run the benchmarks, though the default timeout is 30s, so they get killed, and I didn't look into the actual time for them since the Makefile says >2h.

And finally, I can do
```
$ meson devenv -C build python3
Python 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 12.0.1 20220308 (Red Hat 12.0.1-0)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyshtools import _SHTOOLS
>>> 
```
but of course can't import any of the rest of the Python stuff since I haven't done any of the PEP518 things.

**Comment by eli-schwartz** [comment]
https://github.com/mesonbuild/meson-python provides the PEP 517 build backend used in SciPy, it should be fairly straightforward too.

**Comment by QuLogic** [comment]
I've put this together in #380; there are probably some improvements to be made, but it at least builds wheels now.

**Comment by MarkWieczorek** [comment]
I am going to close this issue now that the latest release v4.11.10 uses the meson backend. 

**Neverthless**, even though pyshtools compiles fine in the CI tests on this repo, and it also compiles fine on macOS and linux desktops, I note that we are encountering problems building the conda feedstock package and also creating wheels for pypi. Some issues are LAPACK/BLAS related, whereas other issues appear to be macOS specific. If you want to help out, see the comments in this issue: https://github.com/SHTOOLS/SHTOOLS/issues/417
