### ISSUE TITLE
Cannot install M1-Mac by pip

### ISSUE THREAD

**Issue by arafune** [SHTOOLS/SHTOOLS#409]
'pip install pyshtools does' not work.  Below is the error message.

Collecting pyshtools
  Using cached pyshtools-4.10.4.tar.gz (38.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      <string>:20: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Traceback (most recent call last):
        File "/Users/arafune/env/py311/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/arafune/env/py311/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/arafune/env/py311/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/mc/kfbp9b8x3k3bd6fq7hychpc00000gn/T/pip-build-env-32ulmxql/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/mc/kfbp9b8x3k3bd6fq7hychpc00000gn/T/pip-build-env-32ulmxql/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/mc/kfbp9b8x3k3bd6fq7hychpc00000gn/T/pip-build-env-32ulmxql/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/mc/kfbp9b8x3k3bd6fq7hychpc00000gn/T/pip-build-env-32ulmxql/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 24, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


--------------

I have already installed 'numpy', but No module named numpy error appears. 

**System information**
OS: Mac SOnoma 14.0
Chip: M1 Ultra
Python: 3.11.5

**Comment by MarkWieczorek** [comment]
Hi. Unfortunately, we don't have M1 wheels for pyshtools. You can find all available wheels here: https://pypi.org/project/pyshtools/#files

There appears to be some sort of problem with the multibuild machinery for M1. If you are really interested, you could take a look here: https://github.com/SHTOOLS/build-shtools and look at the latest github actions logs.

**Comment by albrigc** [comment]
@MarkWieczorek I am getting the same error but am not using an M1 chip, but rather a ryzen 7 7700X. Is my chip also causing an issue? I am also using a newer version of python ( 3.12.0)

**Comment by MarkWieczorek** [comment]
Could you let me know if you are having this problem with the newest release (4.11.10)? I note that there are no wheels available (only source distribution), but `pip install pyshtools` should build fine if all the dependencies are installed.
