### ISSUE TITLE
Install issue can't build wheel. (Using Pycharm)

### ISSUE THREAD

**Issue by albrigc** [SHTOOLS/SHTOOLS#413]
'pip install pyshtools does' not work, and pycharm install not working. Below is error code. Also tried in vscode and same error

Collecting pyshtools==4.10.4
  Using cached pyshtools-4.10.4.tar.gz (38.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [21 lines of output]
  <string>:20: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  Traceback (most recent call last):
    File "C:\Users\chand\PycharmProjects\pythonProject\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\chand\PycharmProjects\pythonProject\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\chand\PycharmProjects\pythonProject\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\chand\AppData\Local\Temp\pip-build-env-jj25qmhw\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\chand\AppData\Local\Temp\pip-build-env-jj25qmhw\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "C:\Users\chand\AppData\Local\Temp\pip-build-env-jj25qmhw\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
      super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
    File "C:\Users\chand\AppData\Local\Temp\pip-build-env-jj25qmhw\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 24, in <module>
  ModuleNotFoundError: No module named 'numpy'
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**System information**
OS: Windows 11
Using PyCharm
CPU: AMD 7 7700X

**Comment by MarkWieczorek** [comment]
Hi there. Could you let me know which version of python you are using? At this point, we don't have a version that works with 3.12, but we do plan on releasing a 3.12 compatible version in about a week if all goes well...

**Comment by MarkWieczorek** [comment]
I am going to close this issue as it is likely outdated. We just put out a new release today (4.13.1) so please try updating. If you have any further problems, please open a new issue.
